config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'shops#index'
  get '/curators', to: 'curators#index'
  get '/contribute' => 'pages#contribute'
  get '/:id', to: 'shops#show'
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :shops
end

app/models/curator.rb
class Curator < ActiveRecord::Base
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :city
  belongs_to :writer, :class_name => "Curator"
  belongs_to :photographer, :class_name => "Curator"
  validates :city, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/curators_controller.rb
class CuratorsController < ApplicationController
  def index
    @curators = Curator.all.order(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all.order(:slug)
  end

  def show
    @shop = Shop.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    redirect_to '/404'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/curators/index.html.erb
<% content_for :meta do %>
  <title>Curation Team | Latte</title>
  <meta name="description" content="">
<% end %>

<div class="container mt4 mb4">
  <article>
    <header class="center">
        <h1 class="h1 sans-serif caps">Curation team</h3>
        <hr class="hr m2 wrap">
    </header>

    <div class="row">
      <% @curators.each do |curator| %>
        <section class="col col-4 center mobile-block" id="<%= curator.name %>">
          <div class="p2">
            <%= image_tag("https://avatars.io/twitter/#{curator.twitter}/128x128px", class: "full-width circle", alt: curator.name, style: "height: auto;", width: 800, height: 800) %>
            <h2 class="h3 caps regular sans-serif m0"><%= curator.name %></h2>
            <h3 class="small regular m0"><%= curator.title %></h3>
            <p class="small"><%= link_to "@#{curator.twitter}", "https://twitter.com/#{curator.twitter}", alt: "Follow #{curator.name} on Twitter" %></p>
          </div>
        </section>
      <% end %>
    </div>
  </article>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="apple-mobile-web-app-title" content="Latte">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon.png" />
    <meta name="viewport" content="initial-scale = 1, user-scalable = no">
    <link rel="stylesheet" type="text/css" href="//cloud.typography.com/6326032/755624/css/fonts.css" />
    <%= yield :meta %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <style>html { -webkit-text-size-adjust: 100%; }</style>
    <script type="text/javascript">
      if(("standalone" in window.navigator) && window.navigator.standalone){
        var noddy, remotes = false;
        document.addEventListener('click', function(event) {
          noddy = event.target;
          while(noddy.nodeName !== "A" && noddy.nodeName !== "HTML") {
            noddy = noddy.parentNode;
          }
          if('href' in noddy && noddy.href.indexOf('http') !== -1 && (noddy.href.indexOf(document.location.host) !== -1 || remotes))
            {
              event.preventDefault();
              document.location.href = noddy.href;
            }
        },false);
      }
    </script>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller.controller_name + "-" + action_name %>">
    <!--[if lt IE 8]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <%= yield %>

    <% unless current_page?(controller: "shops", action: "index") %>
      <%= render "shared/footer" %>
    <% end %>

    <script>
      (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
                                                              function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
      e=o.createElement(i);r=o.getElementsByTagName(i)[0];
      e.src='//www.google-analytics.com/analytics.js';
      r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
      ga('create','UA-24725855-3','auto');ga('send','pageview');
    </script>
  </body>
</html>

app/views/pages/contribute.html.erb
<% content_for :meta do %>
  <title>Curation Team | Latte</title>
  <meta name="description" content="">
<% end %>

<div class="container mt4 mb4">
  <article>
    <header class="row">
      <div class="col col-8 prose">
        <h1 class="h1 sans-serif caps">Contribution guidelines</h3>

        <hr class="hr m2 wrap">
      </div>
    </header>
    <section class="row">
      <div class="col col-8 prose">

        <p class="first">So you want to write some copy? Pull up a seat, you’ve come to the right place. But don’t be nervous: this is just a guide to help you write interesting and informative content that suits Latte. It’s more important to be clear, concise, and relevant than get caught up in the technicalities of an oh-so-boring style guide.</p>

        <h3 class="h2 sans-serif caps">Voice &amp; Tone</h3>

        <p>Latte’s voice is human, and it should sound like a trusted friend who’s giving you the goods. It’s an honest voice with an approachable tone, and it literally speaks to the reader using words like “you” (“you just have to go” “the first thing you’ll notice”). While the voice is human, it’s also third person, so avoid references like “we” (“we love the cappuccino” or “our favourite beans”) and instead focus on the coffee shop (“They make a mean cappuccino” or “The most popular beans”).</p>

        <p class="p">Coffee is casual, inviting, and loved by pretty much everyone, so your copy should reflect that. It’s not informal, but it is smart and educated. Don’t be afraid to add a little spunk to your writing: you want to keep the reader engaged past the first paragraph, and using language that they actually use is an excellent way to do this.</p>

        <h3 class="h2 sans-serif caps">Grammar &amp; Spelling</h3>

        <p class="p">Use what your 3rd grade teacher gave you! Also known as common grammatical sense. The one thing you will notice across Latte though, is that we use the highly controversial practice of the <a href="http://imgur.com/fycHx">Oxford Comma</a>. As far as spelling goes, we use American English, which means no extra “u’s” in color, favorite, and so forth.</p>


        <h3 class="h2 sans-serif caps">Writing Tips</h3>

        <p class="p">The best way to write in the Latte tone is to read all of the copy, read it again, pretend you’re going somewhere and want to know about coffee, and then just write. After you have your basics, re-read your copy and look for opportunities to make it more fun and casual. But be careful: too much wit and not enough substance never gets anyone going. The posts should be easy to digest and quick to scan, generally using the <a href="http://en.wikipedia.org/wiki/Inverted_pyramid">inverted pyramid</a> with a catchy and interesting <a href="http://en.wikipedia.org/wiki/Lead_paragraph">lede</a>.</p>

        <h3 class="h2 sans-serif caps">Interviewing &amp; Research</h3>

        <p class="p">The easiest way to learn about a coffee shop is through both an interview and research. Make sure you include information like which beans they brew (micro-roastery vs multi-roastery, how do they serve drip coffee?), what kind of food is served,  what the aesthetic is like, and how the vibe feels (can you camp out there on the wifi all day?). Draft up sample questions beforehand, such as “what is the first thing you notice when you walk in?” or “who would you bring here with you: a date, your mom, your awkward nerdy cousin?”</p>

        <h3 class="h2 sans-serif caps">More Resources</h3>

        <ul>
          <li><a href="http://mailchimp.com/about/style-guide/">Mailchimp Style Guide</a></li>
          <li><a href="https://medium.com/@Medium/medium-style-sheet-4ea454b6b224">Medium Style Sheet</a></li>
        </ul>
      </div>
      <div class="col col-4 prose">
        <h3 class="h3 sans-serif caps">Small errors</h3>
        <p><small>Best to send us an <a href="mailto:hello@latteup.com">email</a> or a quick <a href="https://twitter.com/dripstrcoffee">tweet</a> so that we can get things updated.</small></p>
        <h3 class="h3 sans-serif caps">Design &amp; Development</h3>
        <p><small>Latte is an open-source effort. To help us build the future, contribute through <a href="https://github.com/simplecasual/latteup.com">Github</a>.</small></p>
      </div>
    </section>
  </article>
</div>

app/views/shared/_footer.html.erb
<footer class="center leading-3 mb4">
  <hr class="hr m2 wrap">
  <span class="mr1 mobile-block small"><%= link_to "Latte", root_path, alt: "Latte, coffee guide" %></span>
  <span class="mr1 mobile-block small"><%= link_to "Curators", curators_path, alt: "Curation Team for Latte" %></span>
  <span class="mr1 mobile-block small"><%= link_to "Contribute", page_path("contribute"), alt: "Contribute to Latte" %></span>
  <span class="mr1 mobile-block small"><%= link_to "Contact", "mailto:hello@latteup.com", alt: "Say Hello to Latte" %></span>
  <br>
  <span class="mr1 mobile-block small"><%= link_to "Twitter", "https://twitter.com/dripstrcoffee", alt: "Follow @dripstrcoffee on Twitter" %></span>
  <span class="mr1 mobile-block small"><%= link_to "Instagram", "https://instagram.com/dripstr", alt: "Follow @dripstr on Instagram" %></span>
  <p class="small mid-gray mobile-hide p1">
    &copy; <%= Time.now.year %> Simple Casual. All rights reserved.
  </p>
</footer>

app/views/shops/index.html.erb
<% content_for :meta do %>
  <title>Latte, Coffee guide</title>
  <meta name="description" content="">
<% end %>

<div class="left coffee-square white">
  <div class="table-cell center p4">
    <h1><%= image_tag('latte-logo.svg', class: 'fit pull-down', alt: 'Latte') %></h1>
  </div>
</div>

<% @shops.each do |shop| %>
  <%= link_to shop.slug, class: "left coffee-square white" do %>
    <div class="coffee-bg" style="background-image: url(<%= shop.cover %>);"></div>
    <div class="center table-cell">
      <h2 class="h1 sans-serif caps m0"><%= shop.name %></h2>
      <h3 class="h4 regular"><%= shop.city.name %></h3>
    </div>
  <% end %>
<% end %>

app/views/shops/show.html.erb
<% content_for :meta do %>
  <title><%= "#{@shop.name}, #{@shop.tagline} | Latte" %></title>
  <meta name="description" content="">
<% end %>

<header class="coffee-header" style="background-image: url(<%= @shop.cover %>)">
  <section class="container px2">
    <div class="block-headline">
      <h1 class="h1 caps regular sans-serif m0"><%= @shop.name %></h1>
      <h2 class="h3 mid-gray regular sans-serif caps m0"><%= @shop.tagline %></h2>
    </div>
  </section>
</header>

<article class="container px2">
  <div class="row">
    <section class="col col-8 prose">
    <h2 class="regular m0 small mb2 author">
      <span class="italic">Writing by</span>
      <%= link_to @shop.writer.name, "https://twitter.com/#{@shop.writer.twitter}", alt: "Follow #{@shop.writer.name} on Twitter", class: "h3 caps sans-serif" %>
      <span class="italic">Photographs by</span>
      <%= link_to @shop.photographer.name, "https://twitter.com/#{@shop.photographer.twitter}", alt: "Follow #{@shop.photographer.name} on Twitter", class: "h3 caps sans-serif" %>
    </h2>

    <div class="dropcap prose">
      <%= @shop.prose.html_safe %>
    </div>
    </section>

    <aside class="col col-4 mobile-block">
      <ul class="mid-gray small list-simple">
        <li>
          <label>Location</label>
          <%= @shop.location %>
        </li>
        <li>
          <label>Seating</label>
          <%= @shop.seating %>
        </li>
        <li>
          <label>Now Playing</label>
          <%= @shop.now_playing %>
        </li>
        <li>
          <label>Noise Level</label>
          <%= @shop.noise_level %>
        </li>
        <li>
          <label>Wifi</label>
          <%= @shop.wifi %>
        </li>
        <li>
          <label>Bathroom</label>
          <%= @shop.bathroom %>
        </li>
        <li>
          <label>Attire</label>
          <%= @shop.attire %>
        </li>
      </ul>
    </aside>
  </div>
</article>

<article class="measure wrap px2">
  <section class="center">
    <hr class="hr m2 wrap">
    <p class="h3 regular m0 sans-serif caps"><%= link_to "&larr;All Coffee Shops&mdash;".html_safe, root_path %></p>
  </section>
</article>